[project]
name = "strategiclearning"
version = "0.1.0"
description = "Strategic learning for AI training"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.4.1",
    "vllm>=0.8.1",
]
